### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by AnonymousPuppy** [MSourceCoded/Quantum-Anomalies#5]
Using forge .1236, a custom modpack, and quantumAnomalies-1.7.10-0.0.3-UNIVERSAL. I got a crash on a server. From the looks of it, it crashed when attempting to generate the anomaly biome. 

Here is the crash report: http://pastebin.com/DG5fqrAT

Please fix this ASAP, thanks.

**Comment by AnonymousPuppy** [comment]
Is this fixed in the latest update that came out today?

**Comment by MSourceCoded** [comment]
Yes, this is fixed in 0.0.4
